### ISSUE TITLE
CLI command to generate images doesn't work

### ISSUE THREAD

**Issue by kvaleev** [imagineui/imagineui#10]
I get an error trying to generate a picture out of ImagineUI digram.

Steps to reproduce:

1. `npm install -g puppeteer`
2. `git clone git@github.com:imagineui/imagineui.git`
3. `cd imagineui`
4. `yarn`
5. `yarn start --input=~/imagineui_sandbox/test.scene --output=~/imagineui_sandbox/test.png`

> imagineui working dir and directory with the scene differs

Expected result: generated image

Actual result: error

```
yarn start --input=~/imagineui_sandbox/test.scene --output=~/imagineui_sandbox/test.png
yarn run v1.22.4
$ yarn workspace imagineui-cli start:built --input=~/imagineui_sandbox/test.scene --output=~/imagineui_sandbox/test.png
$ node ./build/bundle.js --input=~/imagineui_sandbox/test.scene --output=~/imagineui_sandbox/test.png
error: unknown option `--output'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node/13.13.0_1/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js start:built --input=~/imagineui_sandbox/test.scene --output=~/imagineui_sandbox/test.png
Directory: /Users/user/Codebase/imagineui/packages/imagineui-cli
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by v4dkou** [comment]
@kvaleev Thanks for the report!

I've actually forgot to update the docs, the latest version currently uses `--outputDir` instead because of the latest batch rendering feature. Basically you can add as much `--input` directives as you like, and the generated images will be placed in this output directory, taking the name of the original .scene file + '.png'.

P.S. I've had issues on Linux with the CLI not respecting `~` as a shorthand for home directory, and I've used full path to it for testing instead; I will definitely fix this in July, when I plan to continue working on ImagineUI, but if you want to check it out today, please make sure to write a full path to your home folder instead of `~`
