### ISSUE TITLE
Static file generation without need for react

### ISSUE THREAD

**Issue by JoshuaBehrens** [imagineui/imagineui#34]
It would be great to integrate this into any page without the need to get all of react into it. I can imagine, that the current state can work completely with templating engines like twig, handlebar or pug or so. I can imagine this being a lightweight implementation.

**Comment by v4dkou** [comment]
@JoshuaBehrens ImagineUI uses Preact, which is a 3kb reimplementation of React

I have chosen a React-like library to abuse it's tree-like structure to skip writing AST (abstract syntax tree) traversal.

String template engines, like Twig (or, more commonly used in JS world, EJS) are inherently linear, and I would have to reimplement tree traversal, which might not actually come out much lighter than Preact, especially considering features like highlighting the line corresponding to a drawn element on hover in sandbox (and the upcoming VSCode plugin).

Admittedly, right now the core bundle of ImagineUI needs trimming, as I hastily configured Webpack in a bad way, such that it bundles a lot of code that's not really necessary for ImagineUI to work.

If you agree with my reasoning, I will close this issue and open another. ("Trim `imagineui-core` bundle")

If you have other concerns in favour of switching HTML generation to string template engines, I am happy to discuss them!

P.S. Now that you mention integration of ImagineUI into pages, I should say that current documentation is lacking and it's to be resolved circa January-February 2023.

**Comment by JoshuaBehrens** [comment]
Hi @v4dkou and thank you for your quick reaction. I must admit the repo looked a bit stale. Glad it is not :)

So I have two parts why I think it is a good idea. Or at least I thought it was good before your explanation 😅 

1. I think it is good to get away from React due to the need for a browser to render this into HTML at all. I know SSR exists but I am not experienced in nodejs Frameworks, that much I wouldn't know what the cost (of time and complexity) for that is. I know I failed once with this so I think it is heavy lifting one might not need.
2. I don't know React but I know Vue. And I only had to use Vue so far because frequent changing DOM structures in very interactive pages are solved with ease with virtual DOM frameworks like these. But I don't see any insane DOM changes. So for know the only moving parts are CSS hover effects. And I doubt one need 3k of any JS for the final client to look at some fancy hovers.

I see that JS helps with that hover-element-to-highlight-line-of-code feature. My first point is likely a detail how to reach the second point to just have some HTML and CSS so let's ditch that for a moment. String templating is just one solution like SSR to get there.

Yes, I really liked the output of the scenes and think about integrating it into documentation pages. As the current CLI output is just a PNG, that also needs puppeteer (great tool but quite heavy), I thought about the static HTML rendered scenes as output so one could also apply some changes to some coloring or use a different font (thinking about darkmode rendering). Well something you can't do with a PNG, rather an SVG or a styleless HTML snippet.

**Comment by v4dkou** [comment]
@JoshuaBehrens 
> But I don't see any insane DOM changes. So for know the only moving parts are CSS hover effects. And I doubt one need 3k of any JS for the final client to look at some fancy hovers.

We need to have separate discussions about the final output, SSR and the sandbox/editor environment.
For the sandbox/editor, there's benefit in only re-rendering parts of the wireframe that were just changed in the ImagineUI source file in the sandbox, that's how it achieves "draw as you type" feel. That 3k also includes AST traversal as I have mentioned before, etc.

For the final output to be embedded into a documentation webpage, sure, Preact is not really needed, but neither it is used!

Please take a look at how `imagineui-cli` does it, it uses the SSR `preact-render-to-string` package to produce HTML from the Preact tree inside Node.js context and then passes HTML to puppeteer for rendering. 
https://github.com/imagineui/imagineui/blob/master/packages/imagineui-cli/src/template.tsx
https://github.com/imagineui/imagineui/blob/master/packages/imagineui-cli/src/app.tsx

`imagineui-cli` actually only uses `puppeteer` for rendering because of the `wired-elements` library (which renders squiggly Balsamiq-like lines via Shadow DOM). Once I figure out a good way to re-use `wired-elements` library without Shadow DOM and embed fonts in SVG, I will add an option to produce SVG outputs to `imagineui-ssr` and `imagineui-cli`.

I am also considering extracting the SSR solution to a separate `imagineui-ssr` package for convenience of integration into other APIs.
If you don't use Node.JS, here's an example of integration of ImagineUI to Foliant (documentation generation tool written in Python). 
https://github.com/imagineui/foliantcontrib.imagineui
It also suffers from using `puppeteer` as you rightly pointed out, making documentation builds a bit slower and CI/CD configuration a tad harder. 

> one could also apply some changes to some coloring or use a different font (thinking about darkmode rendering)

Full support for styling is in the works, specifically for dark mode (because VSCode plugin is in development, and at this point the bright sandbox preview looks really out of place)

> thank you for your quick reaction. I must admit the repo looked a bit stale. Glad it is not :)

And thanks for your interest in ImagineUI!

There were recent interesting commits, kinda lost behind "Fixed ESLint warnings preventing CI builds" and other unsubstantial changes visible from the home page in GitHub.

Here: [[WIP] Size directives prototype (starting "filling the screen")](https://github.com/imagineui/imagineui/commit/082df87437e6cbdb3099f531edb27805a971cdcb)

This is how I am trying to tackle the dreaded [Block composition](https://github.com/imagineui/imagineui/issues/8) issue, to some interesting results which are going to be reflected once I finish VSCode plugin, documentation and new landing page.
Feel free to participate in a discussion there, create more issues and suggest features/technical solutions.

For instance, which documentation tool would you like ImagineUI to be integrated into?
We have Confluence and Sphinx on our roadmap, do you have any other requests?
https://trello.com/b/vJbtfC6o/imagineui

**Comment by JoshuaBehrens** [comment]
I am working with mkdocs a lot but as lots of people try github pages as well I think this is a target platform I want to suggest as well. We already integrated plantuml into that by rendering all .puml files into .png and just embed them. So for now imagineui could do the same for us right now as well, but when there are features like hover effects, then I would prefer svg as well.
As I am used to JetBrains IDEs I think about an integration like the plantuml integration for imagineui as well.

I really like format so far. I am also following your changes here so I am happy to see updates. Unfortunately I am rather used to frontend JS than CLI JS so I might not be able to help you on the code side of life. Whatever supports this project though I might be able to add some value to this as well.

**Comment by v4dkou** [comment]
@JoshuaBehrens 
> I am working with mkdocs a lot but as lots of people try github pages

By GitHub Pages you mean Jekyll, the standard static site generator in GHP, not the static HTML hosting platform itself, correct? If so, sure Jekyll is a great target to consider!

> We already integrated plantuml into that by rendering all .puml files into .png and just embed them.

That's precisely how Foliant integration works, and what I am going to do for the rest of the integrations, then switching them to SVG all at once, whenever I rework the `wired-elements` part.

Re: JetBrains IDE, that is also in our roadmap, as I do development in IntelliJ IDEA myself, and actually have been looking at PlantUML plugins as a reference. However, it's definitely going to be further down the line, as from my poll data from one DocOps community, more tech.writers (not developers) use simpler tools based on VSCode, rather than IntelliJ platform.

> Whatever supports this project though I might be able to add some value to this as well.

ImagineUI has 2 main directions to evolve:
1. Make the core syntax/renderer better
2. Make the ecosystem of tools around it better

The hardest part of making the core turned out to be not the coding part, but just designing the syntax.
I welcome all suggestions I can get on it, and then I can integrate changes to the core myself (if they don't go against the main idea of making a simple, low-fidelity tool), no biggie.

However, if, for instance, you were to create a Jekyll or a MkDocs plugin that works with `imagineui-cli` the way you've described the PlantUML plugin/the way Foliant plugin works, that would be superb, and I will gladly accept it under the `imagineui` GitHub namespace to maintain!

P.S. We have a small group chat in [Telegram](https://t.me/+Vzd4MdVFYhdj3INN) (most participants are Russian-speaking, but nobody would bat an eye if an English-speaking participant appeared) and are assembling an English-speaking server in [Discord](https://discord.com/invite/SXtVqGMs6C)

You would be welcome to join for quicker discussions :)

**Comment by JoshuaBehrens** [comment]
Yes, I mean Jekyll. Static files would be solved anyway.

I understand that VSCode seems to work better for the audience. I am on the developer side. I do write some tech documentation but not as my main tasks. So I don't really feel myself in the DocOps area. But to be fair: I never heard of the term DocOps but it makes sense.

I am really into PHP so I see myself in systems like statamic e.g. which is a static side generator and I am quite into Shopware as a system. So when we see this somehow in the ecommerce branch I could support there. Maybe I also get my Webstorm (which I restructured into a Ruststorm :D ) but I really see myself rather on the language design and integration overall.

**Comment by v4dkou** [comment]
Restructuring this issue as per our discussion above:
 - #35 
 - #36 
 - #37 
 
Long-term tasks like bootstrapping IntelliJ IDEA and Jekyll integration will stay in [Trello](https://trello.com/b/vJbtfC6o/imagineui) for now, until we can

P.S. @JoshuaBehrens has joined Discord and we've moved the discussion of the ecosystem there

Whoever stumbles across this issue, you're welcome to join too!
 - [Discord](https://discord.com/invite/SXtVqGMs6C) (English)
 - [Telegram](https://t.me/+Vzd4MdVFYhdj3INN) (Russian/English)
